### ISSUE TITLE
When Editing a Bounty that is featured and hitting submit: Server Error (500)

### ISSUE THREAD

**Issue by bountyful** [bountyful/bountyfulcoins#12]
URL: http://www.bountyfulcoins.com/bounty/37 

Bitcoin Address: [https://blockchain.info/address/1KBAczoyZtmh2JSvHv6RXbY3mqf78NnK3p](https://blockchain.info/address/1KBAczoyZtmh2JSvHv6RXbY3mqf78NnK3p)

```
2014-03-05 05:38:52,981 - 14885 - INFO requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): blockchain.info
2014-03-05 05:38:53,289 - 14885 - ERROR blockchain_adapter: Could not get balance, server returned: 500 - Checksum does not validate
```

**Comment by asfaltboy** [comment]
does the log contain a stack trace? can you please paste it here please?

**Comment by bountyful** [comment]
@asfaltboy no stack trace in bountyful.logs just below

```
2014-03-05 05:38:51,664 - 14885 - WARNING py.warnings: /usr/local/lib/python2.7/dist-packages/captcha/client.py:6: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
  from django.utils import simplejson as json

2014-03-05 05:38:52,981 - 14885 - INFO requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): blockchain.info
2014-03-05 05:38:53,289 - 14885 - ERROR blockchain_adapter: Could not get balance, server returned: 500 - Checksum does not validate
```

**Comment by asfaltboy** [comment]
@bountyful This is strange indeed, the log rows you provided should only be called from the `decay_balance` command. By the way, I successfully reproduced the issue locally and the fix should be very simple. 

I'm **more worried** about the lack of logging... you should (and on my local machine I do) see something similar to the following whenever you hit that specific issue:

```
2014-03-05 19:40:21,233 - 6828 - ERROR django.request: Internal Server Error: /bounty/1
Traceback (most recent call last):
  File "D:\Users\big\Envs\bounty\Lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
 ....
  File "D:\Users\big\Envs\bounty\Lib\site-packages\django\db\backends\sqlite3\base.py", line 450, in execute
    return Database.Cursor.execute(self, query, params)
IntegrityError: column bounty_id is not unique
```

Additionally, the base settings.py configures a email logging handling for level error (and above). This means that you should have received an email regarding the error with an attached traceback log to the configured (currently the ADMINS setting sets: contact@bountyfulcoins.com).

This email handler is of course dependant on an smtp server being available to send the messages. Most linux machines should have an smtp service (but perhaps not currently running). Please contact me by mail/jabber if you need help with setting it up.
