### ISSUE TITLE
DataError: value too long for type character varying(64)

### ISSUE THREAD

**Issue by bountyful** [bountyful/bountyfulcoins#17]
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 25, in bound_func
    return func(self, *args2, **kwargs2)
  File "/var/www/bountyfulcoins.com/bountyfulcoins/bountyfulcoinsapp/views.py", line 30, in dispatch
    request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/edit.py", line 205, in post
    return super(BaseCreateView, self).post(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/edit.py", line 171, in post
    return self.form_valid(form)
  File "/var/www/bountyfulcoins.com/bountyfulcoins/bountyfulcoinsapp/views.py", line 100, in form_valid
    self.object = form.save(user=self.request.user, request=self.request)
  File "/var/www/bountyfulcoins.com/bountyfulcoins/bountyfulcoinsapp/forms.py", line 92, in save
    bounty.assign_tags_from_string(data['tags'])
  File "/var/www/bountyfulcoins.com/bountyfulcoins/bountyfulcoinsapp/models.py", line 65, in assign_tags_from_string
    tag, created = Tag.objects.get_or_create(name=tag_name.strip())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 154, in get_or_create
    return self.get_queryset().get_or_create(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 388, in get_or_create
    six.reraise(*exc_info)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 380, in get_or_create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 654, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 687, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 232, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 1511, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
DataError: value too long for type character varying(64)
```

**Comment by asfaltboy** [comment]
This occurred when someone attempted to add a bounty tag with a name over 64 chars (max chars). We can solve this by validating the Tag name length in the Bounty.assign_tags_from_string method. Something like this:

```
# new import
from django.core.exceptions import ValidationError

# ... rest of the Bounty model

def assign_tags_from_string(self, string):
    """
    Takes a list of string, by default sepererated by comma,
    and reassigns the tags to this bounty.
    """
    tag_names = string.split(',')
    self.tags.clear()  # remove existing tags before assigning new
    for tag_name in tag_names:
        if len(tag_name) > 64:   # this can be improved by looking up the actual max length in the field
            raise ValidationError("Tag is too long, please enter a tag under 64 characters")
        tag, created = Tag.objects.get_or_create(name=tag_name.strip())
        self.tags.add(tag)
```

**Comment by bountyful** [comment]
Yes. I was thinking why don't we just increase the size of the field to 200? No need to limit it to 64 really. Thoughts

**Comment by asfaltboy** [comment]
Mind you, this is "per tag" name, and tags are supposed to be a short word (or worst case a phrase). Limiting it to 64 chars should be more than enough. Perhaps it should be more obvious ("client side UI"), how to enter tags (i.e comma separated). Anyway, whatever the length, we probably should validate a single tag length anyway to prevent DB errors...
